# L1: 1575.42 MHz, L2: 1227.60 MHz, L3: 1381.05 MHz, L5: 1176.45 MHz
# From AsteRx-m2 reference guide table 4.1.10
sig_num_ref = {
    0: {"sig_type": "L1CA", "constellation": "GPS", "band": 1, "en": True},
    1: {"sig_type": "L1P", "constellation": "GPS", "band": 1, "en": False},
    2: {"sig_type": "L2P", "constellation": "GPS", "band": 2, "en": False},
    3: {"sig_type": "L2C", "constellation": "GPS", "band": 2, "en": True},
    4: {"sig_type": "L5", "constellation": "GPS", "band": 5, "en": False},
    5: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False},
    6: {"sig_type": "L1CA", "constellation": "QZSS", "band": 1, "en": False},
    7: {"sig_type": "L2C", "constellation": "QZSS", "band": 2, "en": False},
    8: {"sig_type": "L1CA", "constellation": "GLONASS", "band": 1, "en": True},
    9: {"sig_type": "L1P", "constellation": "GLONASS", "band": 1, "en": False},
    10: {"sig_type": "L2P", "constellation": "GLONASS", "band": 2, "en": False},
    11: {"sig_type": "L2CA", "constellation": "GLONASS", "band": 2, "en": True},
    12: {"sig_type": "L3", "constellation": "GLONASS", "band": 3, "en": False},
    13: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False},
    14: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False},
    15: {"sig_type": "L5", "constellation": "IRNSS", "band": 5, "en": False},
    16: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False},
    17: {"sig_type": "E1 (L1BC)", "constellation": "Galileo", "band": 1, "en": False},
    18: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False},
    19: {"sig_type": "E6 (E6BC)", "constellation": "Galileo", "band": 6, "en": False},
    20: {"sig_type": "E5a", "constellation": "Galileo", "band": 5, "en": False},
    21: {"sig_type": "E5b", "constellation": "Galileo", "band": 7, "en": False},
    22: {"sig_type": "E5 AltBoc", "constellation": "Galileo", "band": 8, "en": False},
    23: {"sig_type": "LBand", "constellation": "MSS", "band": 0, "en": False},
    24: {"sig_type": "L1CA", "constellation": "SBAS", "band": 1, "en": False},
    25: {"sig_type": "L5", "constellation": "SBAS", "band": 5, "en": False},
    26: {"sig_type": "L5", "constellation": "QZSS", "band": 5, "en": False},
    27: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False},
    28: {"sig_type": "B1", "constellation": "BeiDou", "band": 1, "en": False},
    29: {"sig_type": "B2", "constellation": "BeiDou", "band": 7, "en": False},
    30: {"sig_type": "B3", "constellation": "BeiDou", "band": 6, "en": False},
    31: {"sig_type": "Reserved", "constellation": "", "band": 0, "en": False}
}
# From AsteRx-m2 reference guide definition 4.2.15 Status Blocks
gain_num_ref = {
    0: {"sig_type": "GPSL1/E1", "en": True},
    1: {"sig_type": "GLOL1", "en": True},
    2: {"sig_type": "E6", "en": False},
    3: {"sig_type": "GPSL2", "en": True},
    4: {"sig_type": "GLOL2", "en": True},
    5: {"sig_type": "L5/E5a", "en": False},
    6: {"sig_type": "E5b/B2", "en": False},
    7: {"sig_type": "E5(a+b)", "en": False},
    8: {"sig_type": "Combined GPS/GLONASS/SBAS/Galileo L1", "en": True},
    9: {"sig_type": "Combined GPS/GLONASS L2", "en": True},
    10: {"sig_type": "MSS/L-Band", "en": False},
    11: {"sig_type": "B1", "en": False},
    12: {"sig_type": "B3", "en": False}
}
